### ISSUE TITLE
option to ignore errors?

### ISSUE THREAD

**Issue by gbaumgart** [phated/grunt-dojo#17]
Hi,
could you please add an option to ignore errors during builds? I'd like to pre-compile layers where some packages might be missing on purpose.

**Comment by steveoh** [comment]
I would recommend using the grunt `--force` option.

**Comment by gbaumgart** [comment]
hi, thanks. pretty odd way to do things, ok, if you like i can put this in a PR....

**Comment by steveoh** [comment]
Sorry, maybe I misunderstood your request. A PR might explain it better sure.

**Comment by gbaumgart** [comment]
all it needs would be something like this: 

```js
var child = grunt.util.spawn({
      cmd: 'node',
      args: args,
      opts: opts
    }, function(err, result){
      if(err){
        if(opts.ignoreErrors) {
          console.warn('dojo build error: ' + err);
        }else{
          console.error('dojo build error: ' + err);
          return done(false);
        }
      }
      
      grunt.log.success('Dojo Successfully Built...');
      
      done();
    });
```

**Comment by gbaumgart** [comment]
hi,
it must be options.ignoreErrors, not opts.ignoreErrors (undefined). However, you can remove that if you like,I switched to my own fork.
thanks,
g

**Comment by steveoh** [comment]
@gbaumgart sorry I missed your last comment. Our builds haven't been failing. @stdavis just fixed this little oversight so I'll pop a new version soon.

**Comment by gbaumgart** [comment]
thanks Stevoh!
