### ISSUE TITLE
Profile::resourceTags not called?

### ISSUE THREAD

**Issue by gbaumgart** [phated/grunt-dojo#18]
Hi,
for some reason resourceTags in my profile are not used? However, I am just trying to make the build process ignoring some directories. 
thanks!

**Comment by stdavis** [comment]
Here's an example of how we are successfully using them: https://github.com/agrc/AGRCJavaScriptProjectBoilerPlate/blob/master/src/app/app.profile.js

**Comment by gbaumgart** [comment]
yeah, thanks @stdavis. The problem is that profile.resourceTags.test  is never called...
