### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by steveoh** [phated/grunt-dojo#19]
will you publish this to npm @phated.

Fixes https://github.com/gruntjs/grunt-docs/blob/master/Blog-2016-02-11-Grunt-1.0.0-rc1-released.md#peer-dependencies

**Comment by phated** [comment]
I'll add you on npm. What's your username there?

**Comment by steveoh** [comment]
its the same as here.

**Comment by phated** [comment]
Added, feel free to publish.

**Comment by steveoh** [comment]
thanks.
